In [1]:
# import necessary libraries
import numpy as np
import tensorflow as tf

### Training Phase

In [2]:
# Windows file path with escape characters
file_path = "C:\\Users\\Pasidhu\\Desktop\\Github7\\DeepLearning-Projects\\2)Next word prediction\\cricket.txt"

# Open and read the file
with open(file_path, 'r', encoding='utf-8') as file:
    cricket_history = file.read()

# Print the content to verify
print(cricket_history)


Cricket history is particularly murky and vague as to the exact origins of the game, it is believed to have been born in England in the late middle ages.

Edward III banned a game similar to cricket in 1369, ‘pila baculorea’ or ‘club ball’ as it was known, as he saw it as being a distraction to his war effort.

Derek Birley in his wonderful book, ‘A Social History of English Cricket’ suggests the game came to England with the French during the time of the Norman Invasion, that their word ‘criquet’ was the dialect name for a variation of club ball, the game Edward the III had sought to eradicate.

There is record of the word ‘creag’ as a derivative of the word creaget in 1299-1300 in the Royal Wardrobe Accounts, for the then Prince Edward the II to play ‘creag’ and other games.

There is no evidence that creag was the same as criquet, the links are too tenuous and games rarely appear in any records of this time unless the aristocracy were playing them or trying to have them eradicated a

In [3]:
cricket_history[:500]

'Cricket history is particularly murky and vague as to the exact origins of the game, it is believed to have been born in England in the late middle ages.\n\nEdward III banned a game similar to cricket in 1369, ‘pila baculorea’ or ‘club ball’ as it was known, as he saw it as being a distraction to his war effort.\n\nDerek Birley in his wonderful book, ‘A Social History of English Cricket’ suggests the game came to England with the French during the time of the Norman Invasion, that their word ‘crique'

In [4]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([cricket_history])

In [5]:
tokenizer.get_config()['filters']

'!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'

In [6]:
tokenizer.get_config()['word_counts']

'{"cricket": 35, "history": 2, "is": 8, "particularly": 2, "murky": 1, "and": 47, "vague": 1, "as": 25, "to": 45, "the": 148, "exact": 1, "origins": 1, "of": 48, "game": 22, "it": 22, "believed": 1, "have": 4, "been": 4, "born": 2, "in": 57, "england": 15, "late": 1, "middle": 1, "ages": 1, "edward": 3, "iii": 2, "banned": 1, "a": 22, "similar": 2, "1369": 1, "\\u2018pila": 1, "baculorea\\u2019": 1, "or": 5, "\\u2018club": 1, "ball\\u2019": 1, "was": 15, "known": 1, "he": 1, "saw": 7, "being": 8, "distraction": 1, "his": 2, "war": 1, "effort": 1, "derek": 1, "birley": 1, "wonderful": 1, "book": 1, "\\u2018a": 1, "social": 1, "english": 6, "cricket\\u2019": 3, "suggests": 1, "came": 1, "with": 16, "french": 1, "during": 2, "time": 5, "norman": 1, "invasion": 2, "that": 9, "their": 4, "word": 3, "\\u2018criquet\\u2019": 1, "dialect": 1, "name": 1, "for": 19, "variation": 1, "club": 4, "ball": 3, "had": 9, "sought": 2, "eradicate": 1, "there": 3, "record": 1, "\\u2018creag\\u2019": 2, "de

In [7]:
tokenizer.word_index

{'the': 1,
 'in': 2,
 'of': 3,
 'and': 4,
 'to': 5,
 'cricket': 6,
 'as': 7,
 'game': 8,
 'it': 9,
 'a': 10,
 'for': 11,
 'with': 12,
 'were': 13,
 'england': 14,
 'was': 15,
 'its': 16,
 'played': 17,
 'by': 18,
 'that': 19,
 'had': 20,
 'at': 21,
 'is': 22,
 'being': 23,
 'games': 24,
 'saw': 25,
 'they': 26,
 'new': 27,
 'australia': 28,
 'english': 29,
 'playing': 30,
 'first': 31,
 'an': 32,
 'be': 33,
 'between': 34,
 'from': 35,
 'technology': 36,
 'or': 37,
 'time': 38,
 'this': 39,
 'aristocracy': 40,
 'recorded': 41,
 'century': 42,
 'two': 43,
 'on': 44,
 'after': 45,
 'bowling': 46,
 'twenty': 47,
 'have': 48,
 'been': 49,
 'their': 50,
 'club': 51,
 'them': 52,
 'classes': 53,
 'teams': 54,
 'up': 55,
 'match': 56,
 'players': 57,
 'into': 58,
 'began': 59,
 'spread': 60,
 'south': 61,
 'international': 62,
 'only': 63,
 'edward': 64,
 'cricket’': 65,
 'word': 66,
 'ball': 67,
 'there': 68,
 'play': 69,
 'men': 70,
 'way': 71,
 'seen': 72,
 'side': 73,
 'best': 74,
 'becom

In [8]:
input_sequences = []
for sentence in cricket_history.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [9]:
input_sequences[:5]

[[6, 93],
 [6, 93, 22],
 [6, 93, 22, 94],
 [6, 93, 22, 94, 178],
 [6, 93, 22, 94, 178, 4]]

In [11]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

55

In [12]:
# add padding
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))

In [13]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  6, 93, 22])

In [14]:
# divide dataset into feature set (X) and labels (y)
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [15]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 6])

In [16]:
y

array([ 93,  22,  94, ...,  38, 177, 622])

In [18]:
# number of words
num_classes = len(tokenizer.word_index)+1

In [19]:
# one-hot encoding labels
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [20]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [21]:
# model building
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

C:\Users\Pasidhu\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
# compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [24]:
# model training
history = model.fit(X, y, epochs=100)

Epoch 1/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.0688 - loss: 6.2642
Epoch 2/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0777 - loss: 5.6309
Epoch 3/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.0842 - loss: 5.5866
Epoch 4/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.1054 - loss: 5.4689
Epoch 5/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.0875 - loss: 5.4172
Epoch 6/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0821 - loss: 5.3701
Epoch 7/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.0982 - loss: 5.2839
Epoch 8/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.1103 - loss: 5.1473
Epoch 9/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.1177 - loss: 5.0932
Epoch 10/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.1283 - loss: 4.9568
Epoch 11/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.1272 - loss: 4.9428
Epoch 12/100
47/47 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step

### Prediction Phase

In [25]:
input_text = "cricket begin"
for i in range(6):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step
cricket begin the game had been growing both
